source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'NNTalkingData_Example' do
  pod 'NNTalkingData', :path => '../'

  target 'NNTalkingData_Tests' do
    inherit! :search_paths

    
  end
end
